version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "4978:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: snapp
      MYSQL_USER: tina
      MYSQL_PASSWORD: pass
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
